### ISSUE TITLE
Revisit Gravity's approach to layout and spacing

### ISSUE THREAD

**Issue by james-nash** [buildit/gravity-ui-web#148]
During the evolution of the website's design, we've made a number of piecemeal design decisions regarding the layout (max-widths of content, columns, etc.) and spacing (default and custom margins between organisms). Put together, they might have made the UI code in Gravity more clunky than necessary.

Examples:

* Via the `grav-l-container()` mixin and `.grav-o-container` class, we ensure that top-level blocks of a page don't exceed a maximum content width on wide screens. However, there are instances where we have page content that does is further indented by arbitrary amounts - e.g. cards on the location page and the 2 columns of "things we're passionate about" on the home page. If these are intentional, should we standardise the amount of indentation?
* PR #70 reduced the max length of lines of text on large screens. It achieves this via indenting within a containers. Again, should we attempt to standardise this in some way?
* 2 pages have margins above the page footer (to create a gap to the content above) and 2 pages remove the margin (via a modifier class). Is this OK going forward, or do we want to universally remove the margin (and thus also the modifier class) and create space to text above by some other means?
* We have the `.grav-o-section` class to add a margin top. It is only being used on the error page. Perhaps we can eliminate it somehow? Correct margins feel like something that should be "built-in" as long as you use appropriate HTML structures.

There's probably more, but you get the idea.

This story is for the team to revisit these layout decisions and review them holistically:

* Do they make sense together?
* Are they a good foundation for future page layouts (and/or additional projects that may consume Gravity's UI library)?
* Can the CSS and HTML be simplified (e.g. can we eliminate some of modifier and utility classes that have been hastily added?

The output of this investigation is likely to be a set of new stories to update Gravity's code and docs and then to roll out those changes to the website project.

**Comment by james-nash** [comment]
Regarding some kind of grid system for Gravity, my preference is to keep it minimal.

The old-skool grid systems you find in frameworks like Bootstrap tend to require lots of nested contain elements in your mark-up. Back in the day, that was the only way to pull it off. However, nowadays, we we have CSS Grid, which is essentially CSS's native way of doing this. It's widely supported and considerably more powerful than old approaches.

Other than perhaps some of the primitive ingredients - for example a standardised gutter size (perhaps provided as a SASS variable and/or CSS custom property - we don't really need to provide anything to enable sites and apps to layout their pages. With CSS Grid, it's trivially easy to do 2, 3, 4... column layouts without needing a mess of `.container`, `.row`, `.col-2`, etc. classes and elements. A few lines of CSS applied to a single parent element gets the job done.

So, in a sense, Gravity perhaps does not need to provide _any_ grid classes. (Of course, it's docs should still explain why and point people to helpful tutorials, examples, etc.).

That being said, to help less CSS-savvy users cover some basic use-cases, I can see value in providing a very small number of utility classes for convenience.

I decided to prototype an idea along those lines and came up with this:
https://codepen.io/cirrus/pen/MLezer

Applying a _single_ CSS class (`.smart-grid`) lays all out all direct child elements in a grid that automagically creates as many columns as there is space for.

Behind the scenes there is a minimum width for each child element (except when the viewport width is less than that minimum - in that case you have no choice but to be squeezed to the viewport width). As soon as there is enough width to accommodate 2x the minimum plus a gutter between them, you get 2 cols. They then expand equally until there is enough with for 3, at which point it becomes 3 columns. And so on, ad infinitum (so on a 40" monitor you might end up with 10 columns! :-D).

There is a default min-width for child elements, but you can override it via a CSS custom property, `--smart-grid-item-min-width`, on a per-container basis. So, depending what _kind_ of things you're laying out on this magic grid, you can choose an appropriate minimum width.

The CodePen demo is a rough concept and a bit of refinement and tinkering would still need to happen. However, I think this could be a good solution. Perhaps if we provide (an more refined version of) this in Gravity, we don't need anything else!

Thoughts?

**Comment by zsteiner** [comment]
I came across this interesting article recently.
https://cathydutton.co.uk/posts/why-i-stopped-using-sass/

She provides a simple vanilla CSS method for a basic 12 column grid. I'm using a variation (without auto-fill so IE can be supported) on a current project.

`.project {
  display: grid;
  grid-template-columns: repeat( auto-fill, minmax(12em, 1fr) );
  grid-gap: 1em;
}`

**Comment by james-nash** [comment]
Nice. Thanks for sharing, @zsteiner!

IMHO, Gravity does still benefit from SASS. Our code is split over many SASS partials which I think does make it easier to find and maintain things. But, for deployment, we do just want a single CSS file. Also, I like SASS vars for things that will never change or be overridden at runtime and can thus compile to explicit values (for more compact CSS and, probably(?), a teeny-weeny bit less runtime overhead compared to CSS vars). But from a development perspective, it's nice (and less error-prone) to be able to work with SASS vars that have human-friendly names versus "magic values".

That being said, we can and should migrate to modern CSS features in Gravity where it makes sense. Grid is one example. I also have ambitions for a nifty colour-scheme system that would make heavy use of CSS vars (along similar lines to the final example in my "[Tale of Two Buttons](https://medium.com/buildit/a-tale-of-two-buttons-e63185aefd5f)" blog post). More on that in #147, if anyone's interested!

If/when we get a bit more visual design input to Gravity, I'd love it if we could find (tasteful & appropriate) uses for things like CSS shapes and blend-modes. Also, I'd absolutely love_ it if we could get our hands on some variable fonts!

After all, **progressive** is one of Gravity's principles! ;-)

**Comment by james-nash** [comment]
Here's a draft proposal for some core layout conventions/rules for Gravity. This is aspirational - right now we do some of this stuff, but not everywhere. I'm putting it here to hopefully provoke some discussion. Once we're all agreed on how we want to do this stuff, we can start updating the code accordingly.

I've written it like documentation, so that once we're happy with it, we can cut and paste it into a markdown file :-)

Please have a read and provide your thoughts, feedback, question, corrections... in the comments. Thanks!

---

## Per-component rules
The following rules are designed to enable maximum re-use and flexibility of UI components. They also make it easier for future Gravity releases to evolve the overall look and feel, without needing to make lots of per-component changes.

All UI components should:

* **Participate in the normal layout flow**
    * In other words, they should not themselves use things like absolute positioning, be floated or any other CSS technique that takes them out of the normal layout flow.
    * They can and should of course use whatever layout techniques they like internally to lay out their respective child elements and nested components.
* **Not set an explicit width on themselves**
    * Block components should expand horizontally ot fill the space provided by their parent. So standard `display: block;` behaviour or equivalent.
    * Non-block components (e.g. inline ones) should expand horizontally to fit their content
* **Not set an explicit height on themselves**
    * Content within a component must always be fully accessible and should therefore never be cropped or obscured. Generally, the easiest way to achieve this is to simply allow elements to follow their natural behaviour of expanding vertically to fit the content within them.
* **Not set explicit outer margins on themselves**
    * It is the responsibility of global rules and/or parent components to set correct spacing between components. If individual components were to set explicit margins themselves, that would interfere.
* **Not hard code values for space, borders, sizes, etc.**
    * Most of the time the inherited defaults will set the correct widths, heights, font-sizes, etc., so those properties should not be explicitly set unless you intentionally want to override the default.
    * When you do override properties, never hard code the values but instead reference the appropriate SASS variable or CSS custom property provided by Gravity. For instance, don't do `padding: 1rem;` but instead do `padding: $grav-sp-m;`.
    * If none of the available variables give you what you need, please contact the [Gravity maintainers](https://github.com/orgs/buildit/teams/gravity-maintainers) - if there's a good case for it, we can always add more global variables so that others can also benefit from them.
    


## Global layout rules
### Vertical spacing and typography
Our CSS approach is inspired by [Heydon Pickering](http://www.heydonworks.com/)'s "[Axiomatic CSS and Lobotomized Owls](https://alistapart.com/article/axiomatic-css-and-lobotomized-owls)" article.

We therefore have a global "lobotomized owl" CSS rule that sets a default vertical margin _between_ successive block elements. Components and pages are encouraged to just let this rule do its thing as much as possible and only selectively override it when absolutely necessary.

Similarly, all components inherit `font-family` and `line-height` by default. As much as possible you should accept these values. Only override them when you have good reason to do so.


### Max-width for page content
Page contents are generally "boxed in". On small viewports there is a standard outer margin to separate the edge of the screen or browser window from text and other content. But once the viewport exceeds a certain width, that page content gets locked to a fixed width and appears centered within the viewport.

However, occasionally there is a need for "full-bleed" elements that span the entire width of the viewport. This can be tricky to achieve when page contents are boxed in by default since you need to overflow your container. Therefore, by default everything is full-bleed. Page authors must explicitly apply the `grav-o-container` class to their outermost container elements that should be boxed in.

Note that nesting elements with `grav-o-container` is not supported as it will create oversized margins on small viewports.


### Grid system
Gravity uses CSS grid for layout. Unlike classical grid systems found in other frameworks that provide lots "rows and columns" classes, this enables a flatter markup structure. You apply a grid to a container and all of its _direct_ child elements will be laid out on that grid.

Gravity provides a handful of grid preset classes that you can apply to a parent element for common, simple cases:

* _This list is TBD: Just an rough idea for now..._
* `grav-o-grid-classic-12`: Divides area into 12 equal width columns.
    * Grid items default to spanning 12 columns, effectively making them full-width.
    * Grid items can use CSS's `grid-column-start` and `-end` properties to span however many columns they need. _Question: Should we provide some utility classes for stuff like half-width, third-width and quarter-width?_
* `grav-o-grid-smart`: Divides area into as many columns as can fit, based on a minimum width per item.


For more complex layouts, consumers are encouraged to make use of CSS grid directly. It is incredibly capable, widely supported and just all round better than any set of CSS classes we could ever hope to make. However, when doing so, you should take advantage of some SASS variables that Gravity provides in order to preserve visual consistency with other Gravity-powered sites and apps:

* `$grav-sp-grid-gutter`: Default gutter width/height to use between items on a grid
* ... _TBC_ (do we need more than this?)

**Comment by james-nash** [comment]
I think the problems and ideas raised in this issue have either been fixed or superseded by newer issues & PRs:

* The newer website designs and changes going into Gravity NEXT no-longer require extra levels of indentation, so the first point is now redundant.
    * Relatedly, the default layout container issues is now changing as part of: Issue #333 and the proposed implementation in PR #339
* The max length of text lines I think is now a non-issue:
     * The responsive typography we have means we don't get excessive amounts of work per line anyway
     * The "ostentatious type" component intended for longer articles further indents the text and thus cuts down line lengths
     * The `.grav-u-max-word-count-m` utility class is still available for restricting the max width of text blocks.
* Proposed layout changes in PR #339 will mean that we always get margins above page footers and this also matches the refreshed website designs. _Not_ having a margin above the footer is therefore no longer desirable or needed.
* `.grav-o-section` is redundant and will be removed in PR #339. The existing error page layout can be recreated using the recently added padding util classes.

Furthermore, we have now added a mixin and object classes for simple, multicolumn layouts. As per discussions in the comments, for more advanced layouts consumers will be encourages to use CSS grid.

Also, the component rules have now been documented in `gravity-ui-web`'s docs.
