### ISSUE TITLE
Use Lerna?

### ISSUE THREAD

**Issue by james-nash** [buildit/gravity-ui-web#151]
@buildit/gravity-maintainers This one's a bit of random idea, but I'm curious to hear what others think...

The `gravity-ui-sass` repo contains the source code for 2 distinct, but closely related, artefacts:

* Our **UI library** (i.e. the SASS, CSS and assets like the SVG icons), which gets published as an NPM package for others to consume
* The **style guide website** generated via Pattern Lab that showcases the available styles and components and is deployed to http://style.buildit.digital/

We made a conscious decision to bundle them into the same repo because, in practice, they get worked on in parallel. You can't really write CSS styles in a vacuum - you need to create the corresponding HTML structure somewhere so that you can _see_ the result. Likewise, that HTML acts as documentation for consumers - we need to show them what markup is needed for a certain UI component. That's what we use PL for.

I still stand by that decision, but... I wonder if we can make the division of responsibilities in the source code a little bit more explicit.

Currently, we have two main directories under `src/`: `src/ui-lib/` and `src/styleguide/`. However, the build scripts, configs, docs, etc. are all mixed together. Perhaps they too should be divided, based on whether they relate to UI lib or style guide.

I therefore wonder whether it might be worth using [Lerna](https://lernajs.io/) and explicitly dividing ui lib and style guide into separate NPM packages.

Potential advantages would be:

* More explicit and easy-to-understand source code structure (since UI lib and style guide would each have their own directories, `package.json` files and build and test setups)
* The style guide would become an actual consumer of the `gravity-ui-sass` NPM _package_ (as opposed to using its _source code_ directly, as it does today), just like our buildit website is.
    * This would help us identify any usage issues early, before they affect downstream consumers like the website
* Over time, other NPM packages that relate to using Gravity for websites/apps could be added into this repo too.
   * For example, we could split out the stylelint config into its own package and also publish that to NPM, so other projects can use it

If we were to go down this route, I'd suggest renaming the _repo_ to something a bit more generic, perhaps `gravity-ui-web` to reflect the fact that it contains the source code for more than just the `gravity-ui-sass` package.

Thoughts?

**Comment by ThePeach** [comment]
I did not know about Lerna and seems like a neat solution to the problem of having to serve two separate applications. 

This even makes more sense with the idea in mind that one day you might decide to migrate towards a different style guide website, thus replacing patternlab.

My problem would be to make the transition as seamless as possible and have a defined MVP and iterate over that, as I'm assuming part of the re-architecting would be to review certain areas and improve their visualisation, e.g. tokens vs components vs page _"mocks"_.

**Comment by james-nash** [comment]
FWIW, for a personal project I've been doing at home I've created something very similar to what's described in this issue (the code's not public right now - but I'm happy to demo it to people in the office). Basically, I have a Lerna monorepo containing:

* A "UI lib" package - SASS sources that get compiled to CSS. Equivalent to our `gravity-ui-sass` NPM package
* A templates package - A set of Nunjucks templates that can be consumed elsewhere. Also includes as [Fractal](https://fractal.build/)-based pattern library that can be run locally (and theoretically published to a web server). This is analogous to the Patttern Lab-based templates & pattern library build you can do from `gravity-ui-sass`'s _sources_
* A shared Stylelint config
* A shared ESLint config
* A static website - generated by [11ty](https://www.11ty.io/)

The template package's pattern library has an NPM dependency on the UI lib (so it pulls in the compiled CSS into the pattern library site that it builds).

The website has NPM dependencies on both the UI lib (also to consume the same CSS) _and_ the template package (so that the site's pages can `{% include '...' %}` those templates).

Template, UI lib and website packages all also have dependencies on the linter configs as needed.

It's early days, but so far *it works*. For local dev, I can - in the root of the repo - run `npm start` which then, via Lerna, runs the `npm start` for each package that has such a script in parallel. This builds the UI lib, builds the pattern library and builds the site. Fires up local dev servers for pattern library and website. And, it then begins watching the corresponding sources for changes and rebuilds + reloads as needed.

So, I can edit SASS in the UI library package and a few seconds after saving, see those changes live in the pattern library _and_ the website. :-D

This gives me confidence that adopting a similar monorepo setup for Gravity's web-related packages is feasible and can be useful. The main difference versus my setup would be that Gravity would *not* include the Buildit website.

**Comment by james-nash** [comment]
As of the 2.2.0 release earlier today, we _are_ using Lerna so I'm going to close this issue.

https://github.com/buildit/gravity-ui-web/releases/tag/gravity-ui-web-v2.2.0
