### ISSUE TITLE
Section padding inconsistent

### ISSUE THREAD

**Issue by dw-buildit** [buildit/gravity-ui-web#182]
**Describe the bug**
When implementing page layout following the homepage template: http://style.buildit.digital/?p=templates-homepage there is no padding bottom on the last section above the footer.

In the demo in pattern lab no sections are rendered so the problem isn't visible. `<section class="grav-c-hero">` is fine.

On the website there is a `<section class="grav-o-container-banner grav-u-text-centered">` as the final section of the page which is also fine because it adds the padding correctly.

If however you just have a regular `<section>` as the last child of `<main>` it will not add padding and so will be tight against the footer:

<img width="1524" alt="screenshot 2019-02-04 at 16 19 29" src="https://user-images.githubusercontent.com/46753034/52221647-82bc5a00-2899-11e9-91ef-a04809fb6a0c.png">

**Comment by james-nash** [comment]
This should probably be worked on in conjunction with #148

**Comment by james-nash** [comment]
Closing this now as the layout changes in PR #339 resolve this issue. Direct children of `<body>` automatically get space between them via the `* + *` rule now. For edge cases there are also margin utility classes to remove or change the default margin that is applied.
