### ISSUE TITLE
Publish UI library copy to CDN

### ISSUE THREAD

**Issue by james-nash** [buildit/gravity-ui-web#191]
**Is your feature request related to a problem? Please describe.**
Feature request: In addition to distributing Gravity's CSS library via NPM, it would be handy to also publish to a CDN. This would allow consumers to simply add something like `<link rel="stylesheet" href="https://static.buildit.digital/gravity/v1.0.0/gravity.css">` to an HTML file to get started instead of needing to faff about with NPM installs. (and, if we add JS later it could be similar)

I imagine this could be useful for small projects and prototypes since it reduces the intial time and effort to get up and running.

For public sites that only need the out-of-the-box Gravity styles & components, there may even be a performance benefit of referencing a central CDN copy instead of hosting their own versions of those files. As users visit various Buildit properties, those files will have already been cached, so visits to new pages referencing them should load a little faster.

Note that this would be _in addition_ to the current NPM distribution, so more complex use-cases can still do what they do today.

**Describe the solution you'd like**
I'd imagine this would be an additional deployment step in our CI builds that uploads a copy of the pre-compiled CSS, JS and assets to a web server. This should coincide with NPM publishes - i.e. whenever we issue a new release.

This would be an _additive_ process - i.e. previously released versions remain there. Therefore, each new release should be published to a unique URL. Using the version number in the URL's path seems like an obvious choice. Something along these lines perhaps:

* `https://static.buildit.digital/gravity/v1.0.0/...` (where `v1.0.0` corresponds to that release's version)

That way consumers can link to a specific version. Also, the URL is human-readable, which makes it easy to understand what your linking to.

We could configure the HTTP response headers to have a very long cache time (or even mark those resources as "immutable"), so that proxies and browsers are encouraged to not re-request those files again - after all, once published, a release will never change.

Some potential nice-to-haves might include:

* Ability to link to the latest release of a major version. For example, something like: `https://static.buildit.digital/gravity/v1.x/...` could always return whatever the most recently release `v1.x.y` release is. This would allow consumers to always receive the most recent _compatible_ release.
     * For these URLs we'd need to be careful with the cache-related response headers. Clients and proxies should at least revalidate these URLs after a few times so that they successfully pick up new releases.
* Index page(s). It might be a nice touch if visiting `https://static.buildit.digital/gravity/` would show a page containing a list of all currently published releases.

**Comment by thehammeranderson** [comment]
Could use https://aws.amazon.com/cloudfront/ unless there is another option already avail.  I can't imagine this costing more than a few dollars a month to host

**Comment by james-nash** [comment]
Sure. If I'm not mistaken, the Buildit website sits behind the Cloudfront cache, so we're already using it there.

Is this something you fancy looking into for us @thehammeranderson?
