### ISSUE TITLE
Make CDN publish script bail out for non-CDN published packages

### ISSUE THREAD

**Issue by james-nash** [buildit/gravity-ui-web#235]
With the scwitch to a Lerna-based monorepo in PR #224, this repo contains the sources for multiple NPM packages.

Currently, as part of _any_ release, the `scripts/cdn_publish.sh` script will be run. Its purpose is to publish assets from the `@buildit/gravity-ui-web` package to a CDN.

It already ignores versions of other packages when it composes its `index.html` page. However, it will still make that page and upload it every time.

However, if it is only other package(s) being published, it's redundant for it to do those steps. See review comments here: https://github.com/buildit/gravity-ui-web/pull/224#pullrequestreview-231055578

**Describe the solution you'd like**
The script should bail out if only other packages are being published.

**Comment by dw-buildit** [comment]
When we push to `master` (where this script is triggered in travis.yml) there could, in theory, be multiple tagged versions of multiple sub-packages. This needs to work within that framework.

I wonder if there's a more elegant solution on using tags to determine travis scripts as well as `master`. I haven't checked travis' docs but there might be a way of adding more conditions to each script block and/or firing multiple script blocks if multiple conditions are met.
