### ISSUE TITLE
Add latest version URL to CDN

### ISSUE THREAD

**Issue by james-nash** [buildit/gravity-ui-web#237]
**Is your feature request related to a problem? Please describe.**
A copy of Gravity's releases is published to a CDN here: https://static.buildit.digital/gravity-ui-web/

Each version gets a unique URL, e.g. https://static.buildit.digital/gravity-ui-web/v2.2.0/gravity.css

It would be nice if we _additionally_ had URLs that:

* Always point to the latest version, e.g.: `https://static.buildit.digital/gravity-ui-web/latest/...`
* Alaways point to the latest, SemVer-compatible version for each major version number. E.g.:
    * `https://static.buildit.digital/gravity-ui-web/v1.x/...`
    * `https://static.buildit.digital/gravity-ui-web/v2.x/...`
    * etc.

The use-case would be for simple websites or prototypes that want to use the CDN but don't necessarily want to be pegged to a specific release.

**Describe the solution you'd like**
Add URL as per the description. However, one question would be the exact behaviour these URLs should have:

* Should they be temporary (302) HTTP redirect to whatever the latest (compatible) release's URL is? (Note that permanent (301) redirects are inappropriate in this case, since the final location will change over time, so we don't want browsers & search engines storing the final URL)
* Should they return the content directly (so be 200 responses), but set caching headers in such a way that user-agents will revalidate after a sensible period (a few days perhaps - we don't issue new releases _that_ frequently after all)

**Comment by thehammeranderson** [comment]
These asks may be in conflict.  The cache header is attached to the file when it is uploaded, so you get one chance to set it.  If you are going to redirect from a url to that file, you will get that immutable cache expiration and latest really won't mean latests the next time it updates.  The only way I see latest working is by having a physical location with its own cache settings.
