### ISSUE TITLE
Set and track a performance budget

### ISSUE THREAD

**Issue by james-nash** [buildit/gravity-ui-web#238]
**Is your feature request related to a problem? Please describe.**
So far we have not really paid attention to the file size of our CSS, JS and SVG output (and possible font files in future). As Gravity grows, we really ought to though.

**Describe the solution you'd like**
We should set ourselves a performance budget (I think for now just some reasonable file-size thresholds would suffice) and then add some tests to our build that check the output file sizes and error if they exceed the limits we've set ourselves (maybe they can also print warnings if we are getting close to our thresholds).

That way we'll get an early warning that our filesize(s) are getting to big and can then make a decision:
* Optimise the code to shrink it down
* Deprecate and remove rarely used things
* Increase our limits (if we agree that everything in the library is needed and cannot be compressed further)

We should also log this over time (so, maybe having an option to output file sizes somewhere like a JSON file would be good). That way we can one-day make nice graphs showing how our file size has changed over time, add notes to releases about how much bigger (or smaller) the library is versus the last release, etc. etc.

Further reading:
* https://addyosmani.com/blog/performance-budgets/
* https://adactio.com/journal/14355
* http://www.performancebudget.io/

**Comment by thehammeranderson** [comment]
looks like we can get some of this done with bundlesize.  it will test file gzip size and fail the build if limits are exceeded.  i am still looking for anything that will do this and/or report/track but so far have only found something that will report +/- vs the last build as build info in Travis CI.  this may be something we have to build ourselves, but i'll keep researching

**Comment by thehammeranderson** [comment]
Do we have any initial sizes we want to set as limits?
