### ISSUE TITLE
Change default layout proposal

### ISSUE THREAD

**Issue by james-nash** [buildit/gravity-ui-web#333]
**Is your feature request related to a problem? Please describe.**
Currently, Gravity removes all padding and margin from the `body` element (so everthing is "full bleed" by default). The intention is that consumers will use the `grav-o-container` class to box in any top-level elements that should not run up to the edge of the viewport, and also not extend beyond a sensible max width on very wide viewports.

A consequence of this is that a simple page with plain mark-up (e.g. something you might get by rendering markdown to an HTML file) won't be very usable until the author manually boxes in things.

This may seem minor, but it is somewhat at odds with the Gravity ethos applied in most other places which is to have sensible styling defaults that work with plain HTML. Ideally, for simple pages, no classes should be necessary at all. Some well structured HTML should yield a usable (though perhaps non-exciting) page layout.

**Describe the solution you'd like**
To remedy this, I propose the following:

* We make the `body` element behave similar `.grav-o-container` by default. I.e. has a small margin on narrow viewports and a max-width that gets centered on wide viewports. We'd also need to some vertical margin above and below - probably `$grav-sp-m`.
    * This will mean that plain, class-less HTML won't have text that buts up against the edges of the viewport.
    * I mocked it up in a CodePen here: https://codepen.io/cirrus/pen/XvmEoW - note how `body` can be styled and sized just like any other element.
* We then have an object class that undoes this behaviour and thus makes it behave just like it does today. Perhaps call it `grav-o-full-bleed-body`?
    * This essentially makes the current layout behaviour opt-in. Consumers doing so are expected to know what they are doing and make use of `grav-o-container` as needed.
* We'll need to update the layout documentation accordingly.
* We should also add some extra rules to `debug.css` to help people avoid issues.
    * For example, we could flag the use of `grav-o-container` outside of `grav-o-full-bleed-body`.

This will of course be a **breaking change** since existing consumers will need to add the new class or risk their page layouts breaking. But, if we can get this in as part of Gravity NEXT, I think it's Ok since we already have a whole bunch of breaking changes so one more won't be too bad.

**Describe alternatives you've considered**
Not exactly an alternative, but rather a tweak of the above. Considering that `grav-o-container` will now only make sense within `grav-o-full-bleed-body` (or whatever name we settle on), perhaps we should change it to be a BEM-style _element_ class, e.g.: `grav-o-full-bleed-body__content`? That might help reinforce the relationship between the two and their intended usage.

TBH, I was never completely sold on the `grav-o-container` name anyway - it feels a bit too generic for what it is.

**Comment by james-nash** [comment]
Relates to #148

**Comment by bradarnst-buildit** [comment]
This makes good sense to me. I think this is partially down to who you/we think the target audience is. Do we assume everyone is very technical or not? The feature you've described here seems like it would be easier for someone like me (less technical). So, personally, I think it's great. Will most of the target audience/users think the same?

**Comment by james-nash** [comment]
Closing the issue as these proposals have now been implemented by PR #339 and are available in the latest Gravity 3 alpha pre-release (`3.0.0-alpha.7`)
